puts "Estados do Brasil >>>"

State.find_or_create_by(:name=>'Acre'.sem_acento.mb_chars.upcase,:initials=>'AC')
State.find_or_create_by(:name=>'Alagoas'.sem_acento.mb_chars.upcase,:initials=>'AL') 
State.find_or_create_by(:name=>'Amapá'.sem_acento.mb_chars.upcase,:initials=>'AP') 
State.find_or_create_by(:name=>'Amazonas'.sem_acento.mb_chars.upcase,:initials=>'AM') 
State.find_or_create_by(:name=>'Bahia'.sem_acento.mb_chars.upcase,:initials=>'BA') 
State.find_or_create_by(:name=>'Ceará'.sem_acento.mb_chars.upcase,:initials=>'CE') 
State.find_or_create_by(:name=>'Distrito Federal'.sem_acento.mb_chars.upcase,:initials=>'DF') 
State.find_or_create_by(:name=>'Espírito Santo'.sem_acento.mb_chars.upcase,:initials=>'ES') 
State.find_or_create_by(:name=>'Goiás'.sem_acento.mb_chars.upcase,:initials=>'GO') 
State.find_or_create_by(:name=>'Maranhão'.sem_acento.mb_chars.upcase,:initials=>'MA') 
State.find_or_create_by(:name=>'Mato Grosso'.sem_acento.mb_chars.upcase,:initials=>'MT') 
State.find_or_create_by(:name=>'Mato Grosso do Sul'.sem_acento.mb_chars.upcase,:initials=>'MS') 
State.find_or_create_by(:name=>'Minas Gerais'.sem_acento.mb_chars.upcase,:initials=>'MG') 
State.find_or_create_by(:name=>'Pará'.sem_acento.mb_chars.upcase,:initials=>'PA') 
State.find_or_create_by(:name=>'Paraíba'.sem_acento.mb_chars.upcase,:initials=>'PB') 
State.find_or_create_by(:name=>'Paraná'.sem_acento.mb_chars.upcase,:initials=>'PR') 
State.find_or_create_by(:name=>'Pernambuco'.sem_acento.mb_chars.upcase,:initials=>'PE') 
State.find_or_create_by(:name=>'Piauí'.sem_acento.mb_chars.upcase,:initials=>'PI') 
State.find_or_create_by(:name=>'Rio de Janeiro'.sem_acento.mb_chars.upcase,:initials=>'RJ') 
State.find_or_create_by(:name=>'Rio Grande do Norte'.sem_acento.mb_chars.upcase,:initials=>'RN') 
State.find_or_create_by(:name=>'Rio Grande do Sul'.sem_acento.mb_chars.upcase,:initials=>'RS') 
State.find_or_create_by(:name=>'Rondônia'.sem_acento.mb_chars.upcase,:initials=>'RO') 
State.find_or_create_by(:name=>'Roraima'.sem_acento.mb_chars.upcase,:initials=>'RR') 
State.find_or_create_by(:name=>'Santa Catarina'.sem_acento.mb_chars.upcase,:initials=>'SC') 
State.find_or_create_by(:name=>'São Paulo'.sem_acento.mb_chars.upcase,:initials=>'SP') 
State.find_or_create_by(:name=>'Sergipe'.sem_acento.mb_chars.upcase,:initials=>'SE') 
State.find_or_create_by(:name=>'Tocantins'.sem_acento.mb_chars.upcase,:initials=>'TO')