puts "Estados do Brasil >>>"

State.find_or_create_by(:name=>'Acre',:initials=>'AC')
State.find_or_create_by(:name=>'Alagoas',:initials=>'AL') 
State.find_or_create_by(:name=>'Amapá',:initials=>'AP') 
State.find_or_create_by(:name=>'Amazonas',:initials=>'AM') 
State.find_or_create_by(:name=>'Bahia',:initials=>'BA') 
State.find_or_create_by(:name=>'Ceará',:initials=>'CE') 
State.find_or_create_by(:name=>'Distrito Federal',:initials=>'DF') 
State.find_or_create_by(:name=>'Espírito Santo',:initials=>'ES') 
State.find_or_create_by(:name=>'Goiás',:initials=>'GO') 
State.find_or_create_by(:name=>'Maranhão',:initials=>'MA') 
State.find_or_create_by(:name=>'Mato Grosso',:initials=>'MT') 
State.find_or_create_by(:name=>'Mato Grosso do Sul',:initials=>'MS') 
State.find_or_create_by(:name=>'Minas Gerais',:initials=>'MG') 
State.find_or_create_by(:name=>'Pará',:initials=>'PA') 
State.find_or_create_by(:name=>'Paraíba',:initials=>'PB') 
State.find_or_create_by(:name=>'Paraná',:initials=>'PR') 
State.find_or_create_by(:name=>'Pernambuco',:initials=>'PE') 
State.find_or_create_by(:name=>'Piauí',:initials=>'PI') 
State.find_or_create_by(:name=>'Rio de Janeiro',:initials=>'RJ') 
State.find_or_create_by(:name=>'Rio Grande do Norte',:initials=>'RN') 
State.find_or_create_by(:name=>'Rio Grande do Sul',:initials=>'RS') 
State.find_or_create_by(:name=>'Rondônia',:initials=>'RO') 
State.find_or_create_by(:name=>'Roraima',:initials=>'RR') 
State.find_or_create_by(:name=>'Santa Catarina',:initials=>'SC') 
State.find_or_create_by(:name=>'São Paulo',:initials=>'SP') 
State.find_or_create_by(:name=>'Sergipe',:initials=>'SE') 
State.find_or_create_by(:name=>'Tocantins',:initials=>'TO')