
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: db_sigim
  username: postgres
  password: password1234%
  port: 5432

development:
  <<: *default
  #schema_search_path: sigim_dev
  database: sigim_dev_db
test:
  <<: *default
  #schema_search_path: sigim_test
  database: sigim_test_db
production:
  <<: *default
  schema_search_path: sigim_prod
  database: sigim_prod_db
  username: concerne
  password: <%= ENV['CONCERNE_DATABASE_PASSWORD'] %>