FROM node:16-alpine AS builder

RUN yarn install

RUN mkdir /app

WORKDIR /app

COPY sigim-front/package*.json ./ 

RUN npm install

COPY sigim-front/ .

# Empacotar para produção
#RUN npm run build

# Compilar para Dev
RUN npm install -g @vue/cli@latest
RUN npm i vue-template-compiler --save-dev


# Multi-Stage Builds 
FROM node:16-alpine3.13
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app ./

EXPOSE 8080

CMD [ "yarn", "serve" ]