source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.0"

# Secure
gem 'securerandom'

# core
gem 'rails', '~> 7.0.3'
gem 'rack-cors'
gem 'puma', '~> 5.0'
gem 'paranoia'
gem 'jbuilder', '2.11.5'
gem 'kaminari'


# auth
gem 'devise_token_auth', '>= 1.2.0', git: "https://github.com/lynndylanhurley/devise_token_auth"

# cache
gem "bootsnap", require: false

# database
gem "pg", "1.3.5"

# security
gem 'rack-attack'

# time zone data
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

#deployment
group :development, :test do
  #gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'factory_bot_rails'
end

group :development do
  gem 'listen', '~> 3.3'
  gem "letter_opener", "~> 1.7"
  gem 'spring'
  gem 'tty-spinner'
  gem 'faker'
  gem 'cpf_faker'
end

group :test do
  gem 'database_cleaner'
  gem 'guard-rspec'
  gem 'terminal-notifier-guard', require: false
  gem 'codeclimate-test-reporter'
  gem 'rails-controller-testing'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'shoulda-callback-matchers', '~> 1.1.1'
  gem 'spring-commands-rspec'
  gem 'fake_ftp'
  gem 'simplecov'
  gem 'simplecov-rcov'
end